### ISSUE TITLE
Seg fault error

### ISSUE THREAD

**Issue by Tav0** [josephfrazier/prettier_d#1]
Hey @josephfrazier, I just found out about your plugin and I'm trying to use it, but I keep getting a seg fault everytime I save a Javascript file.
`Vim: Caught deadly signal SEGV`
`Vim: Finished.`
`zsh: segmentation fault  vim ol.js`

I installed prettier_d and neoformat. Also using the lines you posted to format in real-time. The segfault doesn't happen if I comment out the lines for real-time formatting.

Another thing I noticed is that if I first save the file `w` and then exit `q` the segfault doesn't happen, but if I do `wq` it happens.

Plugin formats the file fine, but it just throws that error.

Hopefully you can help me out on this, thanks! :)

**Comment by josephfrazier** [comment]
Hi @Tav0, thanks for opening the issue!

> Another thing I noticed is that if I first save the file `w` and then exit `q` the segfault doesn't happen, but if I do `wq` it happens.

Hmm, this makes me think the bug might not be in `prettier_d`. What versions of Vim and Neoformat are you using? You should be able to find the Vim version with `vim --version`. The Neoformat version might be a little trickier to find, but if you can make sure it's the most recent (by uninstalling and reinstalling it), that would help.

**Comment by Tav0** [comment]
@josephfrazier Thanks for the reply! My VIM is 8.0.0636 and neoformat is the latest that is in its repo.

**Comment by josephfrazier** [comment]
Thanks for confirming the versions, they sound recent enough. Can you reproduce the issue on a clean machine, without any other vim plugins/configuration? The easiest way to do this might be by installing vim/node/prettier_d/neoformat inside a Docker container, similar to how I did it here: https://github.com/sbdchd/neoformat/issues/75#issue-224582460

**Comment by Tav0** [comment]
@josephfrazier sorry about that! Been pretty busy these couple of days. I will do this today or tomorrow. Cheers

**Comment by josephfrazier** [comment]
Hey @Tav0, I'm going to close this for now. If you find a way that I can reproduce the bug, feel free to post it and we can go from there. Thanks!
