### ISSUE TITLE
Breaks prettier with TypeScript enum keyword

### ISSUE THREAD

**Issue by alextes** [josephfrazier/prettier_d#11]
Running the following code through `prettier_d` breaks `prettier`.
```ts
enum Direction { North, East, South, West };
```
with:
```
SyntaxError: enum is a reserved word (1:1)
> 1 | enum Direction { North, East, South, West };
    | ^
  2 |
```

The odd thing is, `npx prettier_d --version` explains it's running with the installed version 1.15.3 , yet `npx prettier` handles the above fine. Using the `--parser typescript` flag fixes the issue. My best guess is that `prettier_d` is either setting the parser, blocking `prettier` from inferring the parser to use. Or, somehow strips the information `prettier` relies on to decide to use the typescript parser.

Maybe they use extensions to tell what parser to use, and `prettier_d` is using pipes?? I took a quick look through the code but couldn't pinpoint the issue. Let me know if there's anything more I can do to help.

Thank you for an excellent library 🙌.

**Comment by flybayer** [comment]
Yes, I have the same issue parsing mdx files. Prettier automatically infers the correct parser, but prettier_d does not.

**Comment by josephfrazier** [comment]
I'm guessing this is due to #10

**Comment by alextes** [comment]
Hmm, I wouldn't say so but that issue confuses me a little. Like I said `prettier_d` reports it's using exactly the `prettier` version I have installed (1.15.3), that is also the latest version as of this writing. #10 seems to suggest it is actually not, but I can't tell why.

In any case, the version `prettier_d --version` says it's using (1.15.3) works fine when used directly. I can imagine changing the option passing solves this but only because `prettier_d` starts passing less. I don't pass any options. In fact, the reported issue is with an empty `.prettierrc`.

Somehow `prettier` as a module is not getting what it needs to infer the correct parser as it normally does.

**Comment by alextes** [comment]
ALE seems to [work some magic](https://github.com/w0rp/ale/blob/master/autoload/ale/fixers/prettier.vim#L41) related to setting the parser, but it only does it for certain versions, still not sure why the same doesn't work for `prettier_d`. Don't have time for more than a glance right now but maybe someone else can take a look. Perhaps it's how `prettier_d` prints its version.

**Comment by josephfrazier** [comment]
@alextes, to elaborate a little, `prettier_d` currently does its own argument parsing, which was hardcoded to match an older version of Prettier. However, I'm currently working on making `prettier_d` a fork of Prettier that just forwards all arguments to the latest (merged) Prettier, so I think that should solve your problems. Follow along at https://github.com/josephfrazier/prettier_d/issues/4#issuecomment-450060928
