### ISSUE TITLE
won't pick up parser overrides

### ISSUE THREAD

**Issue by chiefjester** [josephfrazier/prettier_d#14]
**Environments:**
- Prettier Version: v1.17.0 (prettier_d v5.7.4)
- Running Prettier via: ALE
- Runtime: Node v10.8.0 / Node 12.1.0
- Operating System: macOS Mojave 10.14.4

**Steps to reproduce:**

I'm using ALE, and have this in my package.json (I tried .prettierrc as well)

```
  "prettier": {
    "overrides": [
      {
        "files": "*.svelte",
        "options": {
          "parser": "html"
        }
      }
    ]
  },
```

All I'm doing is overriding *.svelte to use the parser html. If I install prettier, it works, but if uninstall it and install prettier_d it won't pick up that config and does nothing.

**Expected behavior:**
Should pickup *.svelte extension to format

**Actual behavior:**
Doesn't format *.svelte extension.

**Comment by josephfrazier** [comment]
Hi @thisguychris, https://github.com/josephfrazier/prettier_d/pull/26 updated `prettier_d` to Prettier 1.19.1. Are you still experiencing this issue?

**Comment by chiefjester** [comment]
Hi, @josephfrazier 👋  thanks for getting back with me. Happy Holidays! I have a different configuration now, and I stopped using `ALE`.

I did try to manually invoke prettier_d and I'm still getting an error. Here's a comparison prettier and prettier_d output:

![Alt text](https://monosnap.com/image/kAuNkISfqVpA9QLqf9hkzTBECpFLAk)

`App.svelte` only contains the basic hello world from the example of svelte:

```html
<script>
	let name = 'world';
</script>

<h1>Hello {name}!</h1>
```

There are a couple of syntax svelte brought, like reactive statements, but I think it's still valid Javascript and prettier has no problem fixing it.

Eg of reactive statement:

```html
<script>
	let count = 1;

	// the `$:` means 're-run whenever these values change'
	$: doubled = count * 2;
	$: quadrupled = doubled * 2;

	function handleClick() {
		count += 1;
	}
</script>

<button on:click={handleClick}>
	Count: {count}
</button>

<p>{count} * 2 = {doubled}</p>
<p>{doubled} * 2 = {quadrupled}</p>
```

**Comment by josephfrazier** [comment]
Oh, I think I might know what the issue is. `prettier_d` is no longer meant to be installed from NPM, as it's now a fork of Prettier. See the deprecation message at https://www.npmjs.com/package/prettier_d:

> prettier_d now uses latest Prettier without extra features, install from github: https://github.com/josephfrazier/prettier_d

What happens if you do this?

```
npm install --save-dev https://github.com/josephfrazier/prettier_d
./node_modules/.bin/prettier_d App.svelte
```

---

I just recently started learning more about Svelte, by the way. Really like what I see so far!

**Comment by josephfrazier** [comment]
I also just published a new major version of `prettier_d` that fails to install, to make it more obvious that the NPM version isn't meant to be used. `npx prettier_d` now shows this

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prettier_d@6.0.0 preinstall: `echo 'Install prettier_d from github instead: https://github.com/josephfrazier/prettier_d' && exit 1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prettier_d@6.0.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by chiefjester** [comment]
Hi @josephfrazier, thank you again for getting back to me, I know it's a holiday. I really appreciate it. 🤗

So a couple of things:

*I'm still getting an error*:
![Alt text](https://monosnap.com/image/Oi8dK9vRTrqJSYik1n97fJwFPZggqQ)

*I've tried installing it via GitHub link, it still somewhat installs `prettier`?*
![Alt text](https://monosnap.com/image/3T6PwrRvY73yB1GGBdruemwcifWzKh)

*There's also a missing readme on the latest published in npm:*
![Alt text](https://monosnap.com/image/KoTmebIrn7rvz3igDUJc6TMqh9Rbry)

I think you have to change your package name inside [package.json](https://github.com/josephfrazier/prettier_d/blob/master/package.json#L2)

Currently, it says `prettier`, If this is meant to be forked and meant to be published in npm, shouldn't it be `prettier_d` instead? Otherwise, it'll just conflict with the current `prettier`?

**Comment by josephfrazier** [comment]
> Hi @josephfrazier, thank you again for getting back to me, I know it's a holiday. I really appreciate it. 🤗

You're welcome! I hope we can get this sorted out.

> So a couple of things:
> 
> _I'm still getting an error_:
> ![Alt text](https://camo.githubusercontent.com/3a505b60fdd7e0f9d2fc00b6c3f3ad8e030ba248/68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f4f6938644b3976525472714a5359696b316e3937664a7746505a67677151)

Hmm, I wonder if you somehow have an npm cache issue that's giving you an older version of prettier_d. Can you post the contents of your `package-lock.json` file?

> _I've tried installing it via GitHub link, it still somewhat installs `prettier`?_
> ![Alt text](https://camo.githubusercontent.com/92b3825dd49d140daca5c8b0ff7b2a41f4b1cb99/68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f3354365077725276593733794231474742647275656d77636966577a4b68)
> 
> _There's also a missing readme on the latest published in npm:_
> ![Alt text](https://camo.githubusercontent.com/e1a61c432cc8572d22e436d0f01e1ba7a5e04d90/68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f4b6f546d656249726e3772767a33696744554a6336544d71683952627279)
> 
> I think you have to change your package name inside [package.json](https://github.com/josephfrazier/prettier_d/blob/master/package.json#L2) ([![](chrome-extension://bcnkgcoohaaaclieohdlkphgfinkgbfm/link-icon.png) 6 hours ago](https://github.com/josephfrazier/prettier_d/blob/f0c987d9152690a9945c201a0d1ea37ccc6e015b/package.json#L2)) [](/josephfrazier/prettier_d/blob/HEAD@{2019-12-27T09:13:09Z}/package.json#L2) ([![](chrome-extension://bcnkgcoohaaaclieohdlkphgfinkgbfm/link-icon.png) 6 hours ago](https://github.com/josephfrazier/prettier_d/blob/f0c987d9152690a9945c201a0d1ea37ccc6e015b@%7B2019-12-27T09:13:09Z%7D/package.json#L2))
> 
> Currently, it says `prettier`, If this is meant to be forked and meant to be published in npm, shouldn't it be `prettier_d` instead? Otherwise, it'll just conflict with the current `prettier`?

Oh, good catch, I wouldn't want `prettier_d` to interfere with any `prettier` installation, so I opened up a PR to fix that: https://github.com/josephfrazier/prettier_d/pull/32

Note that this package is no longer meant to be published in NPM, so we don't have to worry about naming conflicts there (not that I have publish permissions for `prettier` anyway). Instead, you/others should install it from the github url.

**Comment by chiefjester** [comment]
Hello, @josephfrazier 👋 Thank you again for checking back with me.

So I've done a couple of things to make sure it's not the cache.

1. I did a `npm cache clean --force`
2. after that I did a `npm cache verify`
3. made a new repo
4. made a new package.json with overrides setting
5. install via `npm install --save-dev https://github.com/josephfrazier/prettier_d`

I'm still getting an error if I invoke prettier_d
![Alt text](https://monosnap.com/image/uJlSeaST1OBj1wPKgQ5Q9NehB2JRIH)

I also notice that in your [package.json](https://github.com/josephfrazier/prettier_d/blob/master/package.json#L7) `prettier_d` is pointed to `bin/prettier_d.js` as oppose to prettier where it's pointed to `./bin/prettier` Is there a difference?

Here's a copy of my [package-lock.json](https://gist.github.com/thisguychris/94b52b09b3c624023e5a2f5bdcd696a7)

**Comment by josephfrazier** [comment]
Hmm, can you push to repo up to GitHub so I can try to reproduce the issue with the same code?

**Comment by chiefjester** [comment]
sure, @josephfrazier I've set up a test [repo here](https://github.com/thisguychris/test_prettier)

**Comment by josephfrazier** [comment]
Ok, the repo seems fine to me, but I wasn't able to reproduce the issue, unfortunately. You can see what I tried here:

<details>

```
josephfrazier@Josephs-MacBook-Pro:~/workspace$ git clone https://github.com/thisguychris/test_prettier
Cloning into 'test_prettier'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 10 (delta 1), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
josephfrazier@Josephs-MacBook-Pro:~/workspace$ cd test_prettier/
josephfrazier@Josephs-MacBook-Pro:~/workspace/test_prettier$ npm i
npm WARN test_prettier@1.0.0 No repository field.

added 206 packages from 491 contributors and audited 308 packages in 20.634s
found 0 vulnerabilities

josephfrazier@Josephs-MacBook-Pro:~/workspace/test_prettier$ ./node_modules/.bin/prettier_d test.svelte
<script>
  let name = "world";
</script>

<h1>Hello {name}!</h1>
josephfrazier@Josephs-MacBook-Pro:~/workspace/test_prettier$ ./node_modules/.bin/prettier_d test2.svelte
<script>
  let count = 1;

  // the `$:` means 're-run whenever these values change'
  $: doubled = count * 2;
  $: quadrupled = doubled * 2;

  function handleClick() {
    count += 1;
  }
</script>

<button on:click="{handleClick}">
  Count: {count}
</button>

<p>{count} * 2 = {doubled}</p>
<p>{doubled} * 2 = {quadrupled}</p>
josephfrazier@Josephs-MacBook-Pro:~/workspace/test_prettier$
```

</details>

Oh, after seeing the `synchronous-promise` error you posted, I think I've figured it out. The background server invokes the `runPrettier.js` file:

https://github.com/josephfrazier/prettier_d/blob/937a59d837788b176b243b4f0df936f990daa170/lib/server.js#L13

which uses `synchronous-promise`, but that package was only listed as a devDependency, rather than a production dependency. This bug also came up in https://github.com/josephfrazier/prettier_d/issues/28, but I didn't realize what the underlying problem was. I've got a potential fix prepared at https://github.com/josephfrazier/prettier_d/pull/34 and plan to merge it once the tests pass. Can you try again once it's merged?

(I'm guessing I couldn't reproduce the issue because I must have `synchronous-promise` installed globally, likely from previous development work on `prettier_d`)

**Comment by chiefjester** [comment]
Hey, @josephfrazier thanks for staying and knocking this issue out. Looks like moving those `devDependencies` to `dependencies` did the trick.

![Alt text](https://monosnap.com/image/LFsd8bTdSgXRodH0SIO9dMDb9hTDDC)

I guess we can close this issue now? 

Side question: prettier_d is meant to be a fork, does this mean you won't commit to 1:1 parity to its settings and API? I was wondering the reason for not having it published in NPM. 

You could also publish it in Github if you want. Let me know if you need help setting up a Github Actions for that.

**Comment by josephfrazier** [comment]
Thanks for helping me find the root cause of the problem! It was a pretty bad oversight, and I'm thinking I should add an automated test to prevent it from recurring.

> Side question: prettier_d is meant to be a fork, does this mean you won't commit to 1:1 parity to its settings and API? I was wondering the reason for not having it published in NPM.

I actually made this a fork in order to more easily keep up with settings/API changes! You can see more details at https://github.com/josephfrazier/prettier_d/issues/13#issuecomment-455719346, partially reproduced below

> To put it simply, it was easier for me to update prettier_d if it's a fork of prettier (instead of relying on prettier to be installed separately), and if I don't run the build process (because of the way prettier_d overrides some prettier functionality). See https://github.com/josephfrazier/prettier_d/issues/4#issuecomment-450060928 for a bit more context on this change.

**Comment by chiefjester** [comment]
@josephfrazier your welcome, I also appreciate you jumping to my issue and try to work with me, and it's a holiday to boot!

I'm not sure if this is an excellent place to discuss this, or in #13, but a comfortable middle ground [Github Packages](https://github.com/features/packages). Where it doesn't interfere with the `npm` echo system but make it more convenient for users to install since a registry is an optimized form of installing a package as opposed to installing via GitHub repo. Let me know if you are open with the idea, I can create an issue, and we can discuss from there. Happy Holidays!

**Comment by josephfrazier** [comment]
I've been curious to try Github Packages, why don't we continue the conversation in #13? I've reopened it accordingly.
