### ISSUE TITLE
Any plans to support prettier-eslint as the processer?

### ISSUE THREAD

**Issue by clijiac** [josephfrazier/prettier_d#2]
Hi ,do you have any plans to support projects like [prettier-eslint](https://github.com/prettier/prettier-eslint), it has same api with prettier

Thanks for your great lib!

**Comment by josephfrazier** [comment]
Hi @clijiac, thanks for the question! I could be convinced to accept a PR adding `prettier-eslint` support, but it seems like it'd be better to keep this project focused on prettier. You could probably use `prettier_d` followed by [`eslint_d`](https://github.com/mantoni/eslint_d.js) to accomplish the same effect. Example `.vimrc`line:

```vim
autocmd FileType javascript setlocal formatprg=prettier_dnc\ --local-only\ --pkg-conf\ --fallback\ \|\ eslint_d\ --stdin\ --fix-to-stdout
```

**Comment by clijiac** [comment]
hi @josephfrazier , I just make a small change to support `prettier-eslint`

see #3

**Comment by clijiac** [comment]
try to add support for `prettier-eslint` , see #3

**Comment by tunnckoCore** [comment]
@josephfrazier, in anyway, from v4 Prettier-ESLint-CLI is 1:1 with Prettier's CLI, so there's no problem. The only needed and easiest thing to do here is to check if `prettier` exists, then if `prettier-eslint-cli` exists.

**Comment by josephfrazier** [comment]
Hmm, one of the main points of `prettier_d` is to avoid having to use the CLI. I still think it'd be better to just use `prettier_d` + `eslint_d` as described [above](https://github.com/josephfrazier/prettier_d/issues/2#issuecomment-308858753), or even just `eslint_d` (as described in https://github.com/josephfrazier/prettier_d/pull/3#issuecomment-310144872), so I'm going to close this for now.
