### ISSUE TITLE
Error: Cannot find module 'synchronous-promise' when executing `prettier_d`

### ISSUE THREAD

**Issue by trongthanh** [josephfrazier/prettier_d#28]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: CLI
- Runtime: Node 12
- Operating System: macOS

**Steps to reproduce:**
- Install with `yarn global add https://github.com/josephfrazier/prettier_d`
- Try the command with: `prettier_d -v`

**Expected behavior:**
- New version 1.19.1 should be printed.

**Actual behavior:**
```sh
$ prettier_d -v
Error: Cannot find module 'synchronous-promise'
Require stack:
- /Users/trantrongthanh/.config/yarn/global/node_modules/prettier/tests_integration/runPrettier.js
- /Users/trantrongthanh/.config/yarn/global/node_modules/prettier/lib/server.js
```

MORE INFO:

I checked `synchronous-promise` package dependency, it is listed in `devDependencies`, so may be it was skipped during `yarn add`. I re-run `yarn` inside `/Users/trantrongthanh/.config/yarn/global/node_modules/prettier` and it's now working properly.

**Comment by josephfrazier** [comment]
Hi @trongthanh, sorry for the delay here.

I just tested this in a temporary directory by running the following:

```bash
cd $(mktemp -d)

# master branch was https://github.com/josephfrazier/prettier_d/commit/9777144a0a07388fa072516c430229662967ab56 at time of writing
yarn add https://github.com/josephfrazier/prettier_d

./node_modules/.bin/prettier_d -v
```

and I saw `1.19.1` printed out, as expected. Can you confirm that you're still experiencing this issue?

**Comment by trongthanh** [comment]
It's working for me without the `yarn` rerun now. I guess there's a patch update on prettier's side. This issue can be closed.

**Comment by josephfrazier** [comment]
Glad to hear it's working, thanks
