### ISSUE TITLE
Use `core_d`?

### ISSUE THREAD

**Issue by josephfrazier** [josephfrazier/prettier_d#37]
It was extracted from `eslint_d`. See https://github.com/mantoni/core_d.js
and https://github.com/mantoni/eslint_d.js/commit/786d4397128c340a6f5cf4ab300ac246ad802921

**Comment by flybayer** [comment]
I have a lot of problems with prettier_d but eslint_d always works great.

**Comment by josephfrazier** [comment]
Can you elaborate on the problems? `prettier_d` is a fork of `eslint_d`, so I'm curious what you're experiencing.

**Comment by josephfrazier** [comment]
closing, as this project is no longer maintained
