### ISSUE TITLE
prettier_d command hang when execute outside .git project

### ISSUE THREAD

**Issue by trongthanh** [josephfrazier/prettier_d#70]
When executing `prettier_d` (except for `stop|status|restart`) in a project without a .git folder, the command hang forever. And when I use this tool with Sublime Text, the editor also hang.

I tried to debug the issue and noticed that when executing the command outside of project with .git, [the `dataFile` variable in portfile.js](https://github.com/josephfrazier/prettier_d/blob/master/lib/portfile.js#L14) has value `null/.prettier_d`. The `try...catch` over there doesn't help and `dir` got null. The package we use to find project root [`find-project-root`](https://www.npmjs.com/package/find-project-root) is too dated and unreliable. From the docs, it uses `.git` and `.hg` as markers. Therefore, for non-git folders, it returns `null`.

I think we should find an alternative to `find-project-root` with better root project detection. For e.g., I found [`ancesdir`](https://www.npmjs.com/package/ancesdir) may be used to detect a variety of indicators such as `.git`, `package.json`, `.prettierrc`, etc...

**Comment by josephfrazier** [comment]
Hi @trongthanh, thanks for the report! Can you clarify which files you have in your project, that indicate it's the root of the project?

**Comment by trongthanh** [comment]
Hi @josephfrazier, most of my projects have `package.json` (99%) and/or `.git` (90%) and/or `.prettierrc*` (80%). 

I use Sublime Text (with [JsPrettier extension](https://github.com/jonlabelle/SublimeJsPrettier) with this `prettier_d` as executable) to edit and format JS files that may locate inside and outside of "projects".

**Comment by josephfrazier** [comment]
Thanks for the details!

I had missed this part earlier:

> The `try...catch` over there doesn't help and `dir` got null.

I just merged a change that should help the `catch` do better: https://github.com/josephfrazier/prettier_d/pull/71

Can you try reinstalling `prettier_d` from github as described in the readme, and let me know if that helps?

**Comment by trongthanh** [comment]
@josephfrazier, I don't think #71 will fix this. What I meant with "The `try...catch` over there doesn't help and `dir` got null." is that [this line](https://github.com/josephfrazier/prettier_d/blob/master/lib/portfile.js#L9):
```js
dir = findProjectRoot(process.cwd());
```
never throws error even if `prettier_d` is executed outside of `.git` or `.gh`-root folders. It just simply returned `null`, and the [`dataFile` variable at line 14](https://github.com/josephfrazier/prettier_d/blob/master/lib/portfile.js#L14) got `null/.prettier_d`.

**Comment by josephfrazier** [comment]
Oh, I see now. I thought you were saying that the `catch` block was executing and resulting in `null`, but you're saying the `try` block is returning null. I just merged [another change](https://github.com/josephfrazier/prettier_d/pull/72) that I hope will fix things, can you reinstall from github and try again?

**Comment by trongthanh** [comment]
I reinstalled prettier_d with your new change and it works outside of git repo folders now. I think it this issue is fixed.

**Comment by josephfrazier** [comment]
Thanks for confirming! Let me know if anything else comes up
