### ISSUE TITLE
cuts off after a certain number of characters

### ISSUE THREAD

**Issue by MagicDuck** [josephfrazier/prettier_d#83]
Seems like there is a specific buffer size after it will cut off the prettified output

**Comment by josephfrazier** [comment]
Hi @MagicDuck, thanks for the report. Can you provide a way to reproduce the issue?

**Comment by MagicDuck** [comment]
Hi @josephfrazier, first I want to apologize for that minimal issue report, I really appreciate the speed of this tool and your help!
My excuse is that I was pretty tired that day :P

I was trying to use `prettier_d` with https://github.com/iamcco/diagnostic-languageserver. 
In essence, if I do something like the following on the command line:
```bash
cat verylargejsfile.js | prettier_d --stdin --stdin-filepath verylargejsfile.js
```
It will work just fine (Note: `verylargejsfile.js` has like 2000 lines.)
But when I configure it through diagnosticls, it will cut off after a certain number of characters.
For reference, my config for it (in lua as am using it with nvim lsp) was something like:
```lua
prettier =  {
  command = "prettier_d", -- cuts off large files
  --command = "./node_modules/.bin/prettier", -- but this works fine
  args = {"--stdin", "--stdin-filepath", "%filepath"},
  isStdout = true,
  rootPatterns = {".prettierrc", ".prettierrc.json"}
}
```

Now, the thing is that diagnosticls works just fine with the regular `prettier` and also `eslint_d --fix`, so am guessing there might be something to do with how `prettier_d` flushes its output to `stdout`? Either that or something that needs to be fixed in https://github.com/iamcco/diagnostic-languageserver?...

**Comment by MagicDuck** [comment]
Hmm, interesting, this appears not to be an issue with `https://github.com/mikew/prettier_d_slim`

**Comment by josephfrazier** [comment]
Oh, that's good to hear! To be honest, I'm not really maintaining `prettier_d` any more, so if `prettier_d_slim` works for you, I'd encourage you to use that.

**Comment by josephfrazier** [comment]
closing, as this project is no longer maintained
