### ISSUE TITLE
Does not pick up changes in `.prettierrc` without killing `prettier_d/lib/server.js`

### ISSUE THREAD

**Issue by raine** [josephfrazier/prettier_d#9]
```
% prettier_d -v
v1.13.7 (prettier_d v5.7.4)
```

**Comment by josephfrazier** [comment]
Thanks for the report, @raine! I'd be open to any PRs improving this, as it's a known issue. From the readme:

> Note that a `.prettierrc` file will override a `package.json` file, and both will override `.editorconfig`. Also, these files are cached, so if you change them, you'll need to restart the server for the changes to apply: `prettier_d restart`

**Comment by josephfrazier** [comment]
Not sure if this is still a problem for you, @raine, but now that prettier_d uses the latest merged Prettier, any fix would have to take into account Prettier's built-in config caching: https://prettier.io/docs/en/api.html#prettierclearconfigcache

**Comment by josephfrazier** [comment]
Hi @raine, #26 updated prettier_d to Prettier 1.19.1. Are you still experiencing this issue?

**Comment by josephfrazier** [comment]
Oh, also: `prettier_d` is no longer meant to be installed from NPM, as it's now a fork of Prettier. See the deprecation message at https://www.npmjs.com/package/prettier_d:

> prettier_d now uses latest Prettier without extra features, install from github: https://github.com/josephfrazier/prettier_d

**Comment by josephfrazier** [comment]
closing, as this project is no longer maintained
